[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.localnet]
er_state_account = "9ChqoFDgVmmvD6Hcajv2JppVZ7S1qPDozrTw4V7q2yLP"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"

# [test.validator]
# #url = "https://api.devnet.solana.com"
# #url = "https://api.mainnet-beta.solana.com"

# # [[test.validator.clone]]
# # address = "DELeGGvXpWV2fqJUhqcF5ZSYMS4JTLjteaAMARRSaeSh"

# # [[test.validator.clone]]
# # address = "mAGicPQYBMvcYveUZA5F5UNNwyHvfYh5xkLS2Fr1mev"

# # [[test.validator.clone]]
# # address = "EpJnX7ueXk7fKojBymqmVuCuwyhDQsYcLVL1XMsBbvDX"

# # [[test.validator.clone]]
# # address = "7JrkjmZPprHwtuvtuGTXp9hwfGYFAQLnLeFM52kqAgXg"